# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'DouYin' do
  
  pod 'AFNetworking'
  pod 'JSONModel'
  pod 'Masonry'
  pod 'SocketRocket'
  pod 'libwebp'

  target 'DouYinTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DouYinUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
